apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retail-analytics-monitor
  namespace: pedro-sbarainicordei-dev
  labels:
    # Vincula o monitor ao aplicativo e à stack de observabilidade do cluster
    app: retail-analytics
    release: prometheus
spec:
  selector:
    matchLabels:
      app: retail-analytics
  endpoints:
  - port: http # Alinha de volta com o nome textual da porta do seu Service
    path: /q/metrics
    interval: 30s