apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retail-analytics-monitor
  namespace: pedro-sbarainicordei-dev
  labels:
    app: retail-analytics
spec:
  selector:
    matchLabels:
      app: retail-analytics
  endpoints:
  - targetPort: 8080 # Alvo numérico direto para o container
    path: /q/metrics
    interval: 30s
    scheme: http